version: "3"

services:
  server:
    build: .
    container_name: flwr-server
    hostname: server
    command: python server.py
    ports:
      - "8080:8080"
    networks:
      - flnet

  client0:
    build: .
    container_name: flwr-client0
    command: python client.py 0
    depends_on:
      - server
    networks:
      - flnet

  client1:
    build: .
    container_name: flwr-client1
    command: python client.py 1
    depends_on:
      - server
    networks:
      - flnet

  client2:
    build: .
    container_name: flwr-client2
    command: python client.py 2
    depends_on:
      - server
    networks:
      - flnet

networks:
  flnet:

